### ISSUE TITLE
not compatible with M24.5 , PHP 8.1 

### ISSUE THREAD

**Issue by elizad** [sameday-courier/magento-2-plugin#31]
not compatible with M24.5 , PHP 8.1

**Comment by Soptareanu** [comment]
> not compatible with M24.5 , PHP 8.1

What is the issue ?

**Comment by elizad** [comment]
Communication error: Deprecated Functionality: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in vendor/sameday-courier/php-sdk/src/Sameday/SamedayClient.php on line 119
