### ISSUE TITLE
Error issuing the AWB for locker orders

### ISSUE THREAD

**Issue by nanuxp** [sameday-courier/magento-2-plugin#41]
After the update, we receive the following error when trying to issue waybills for locker deliveries:

"lockerLastMile: LockerLastMile dat este invalid (se poate folosi si campul lockerId, dar este deprecated)."

Magento 2.4.3-p3, + plugin v. 1.4.3

**Comment by Soptareanu** [comment]
> After the update, we receive the following error when trying to issue waybills for locker deliveries:
> 
> "lockerLastMile: LockerLastMile dat este invalid (se poate folosi si campul lockerId, dar este deprecated)."
> 
> Magento 2.4.3-p3, + plugin v. 1.4.3

Mesajul este provenit de la API-ul Sameday si semnaleaza ca ID-ul respectivului terminal nu este valid. Pe mediul demo apare foarte frecvent deoarece lista de easyBox-uri nu este sincronizata 1 la 1 cu cea din productie. Pe mediul prod. un mesaj similar de eroare poate sa apara in cazul in care terminalul easyBox ales, la acel moment se alfa in stare inactiva (motivul unor lucrari de mentenanta). Puteti incerca sa trimiteti comanda catre un alt easyBox.

**Comment by nanuxp** [comment]
Este ok acum, am facut update la v. 1.5.0.
Cu 1.4.3 nu am putut emite nici un awb.
